'use client'

import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, CheckCircle2, ChevronRight, Clipboard, Download, RotateCcw, Search, Server, Settings2, ShieldCheck, Terminal, Network, Zap, X, Database, FileText, CircleGauge } from 'lucide-react'

type ControlCenterProps = { activeTab: string; serverCount?: number }

const deployments = [
  { id: 'dep-m7u845h', service: 'analytics-cluster', status: 'Ready', region: 'us-east-1', commit: 'main · a81f29c', runtime: 'Node.js 20', created: '2 min ago' },
  { id: 'dep-m7u83xk', service: 'worker-queue', status: 'Building', region: 'eu-west-1', commit: 'release · 72be101', runtime: 'Node.js 22', created: '18 min ago' },
  { id: 'dep-m7u7z2p', service: 'web-production', status: 'Failed', region: 'us-west-2', commit: 'main · 41c9a7d', runtime: 'Node.js 20', created: '1 hour ago' },
]

const logs = [
  ['12:42:09', 'INFO', 'api-production', 'Deployment health check returned HTTP 200'],
  ['12:41:54', 'INFO', 'worker-queue', 'Job processed successfully in 184ms'],
  ['12:39:18', 'WARN', 'analytics-cluster', 'Memory pressure crossed the 75% threshold'],
  ['12:36:02', 'ERROR', 'web-production', 'Previous build exited with code 1; rollback available'],
]

export function ControlCenter({ activeTab, serverCount = 3 }: ControlCenterProps) {
  const [query, setQuery] = useState('')
  const [range, setRange] = useState('24h')
  const [logLevel, setLogLevel] = useState('All')
  const [noticeRead, setNoticeRead] = useState(false)
  const [showOnboarding, setShowOnboarding] = useState(false)
  const [showDemo, setShowDemo] = useState(false)
  const [rollback, setRollback] = useState<string | null>(null)
  const filteredLogs = useMemo(() => logs.filter(([time, level, source, message]) => `${time} ${level} ${source} ${message}`.toLowerCase().includes(query.toLowerCase()) && (logLevel === 'All' || level === logLevel)), [query, logLevel])

  if (activeTab === 'Incidents') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><AlertTriangle size={13} />Incident center</span><p className="feature-subtitle">Track, assign, and resolve workspace-impacting events.</p></div><button className="primary-action" onClick={() => setNoticeRead(true)}>{noticeRead ? 'All incidents reviewed' : 'Acknowledge all'}</button></div><div className="incident-grid">{[['INC-204', 'Memory pressure on analytics-cluster', 'Critical', 'Dina Ashraf', '18 min ago'], ['INC-203', 'Build failed on web-production', 'High', 'Platform team', '1 hour ago'], ['INC-202', 'Worker queue latency elevated', 'Medium', 'Unassigned', '3 hours ago']].map(([id, title, severity, owner, time]) => <article className="incident-card" key={id}><div className="deployment-card-top"><span className={`incident-severity severity-${severity.toLowerCase()}`}>{severity}</span><span className="table-muted">{id}</span></div><h3>{title}</h3><p>{owner} · {time}</p><div className="incident-timeline"><span>Detected</span><i /><span>{noticeRead ? 'Acknowledged' : 'Investigating'}</span><i /><span>Resolve</span></div><button className="secondary-action" onClick={() => setNoticeRead(true)}>{noticeRead ? 'Resolved locally' : 'Acknowledge incident'}</button></article>)}</div></section>

  if (activeTab === 'Dependency Map') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Network size={13} />Dependency map</span><p className="feature-subtitle">Trace how services affect one another before changing production.</p></div><span className="safe-mode-badge"><ShieldCheck size={13} />Local topology</span></div><div className="dependency-map"><div className="dependency-node node-edge"><Server size={17} /><strong>web-production</strong><span>Ingress · Ready</span></div><div className="dependency-link" /><div className="dependency-node node-core"><Zap size={17} /><strong>api-production</strong><span>Core API · Healthy</span></div><div className="dependency-link" /><div className="dependency-node node-data"><Database size={17} /><strong>analytics-cluster</strong><span>Data layer · Degraded</span></div><div className="dependency-node node-worker"><Terminal size={17} /><strong>worker-queue</strong><span>Async jobs · Healthy</span></div></div><div className="anomaly-banner"><AlertTriangle size={17} /><div><strong>Impact preview</strong><span>Changing api-production may affect web-production, analytics-cluster, and worker-queue.</span></div></div></section>

  if (activeTab === 'Audit log') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><FileText size={13} />Audit log</span><p className="feature-subtitle">Every local control-plane action is traceable.</p></div><button className="secondary-action" onClick={() => navigator.clipboard?.writeText('deployment.created · Dina Ashraf\nincident.acknowledged · Dina Ashraf')}>Copy audit</button></div><div className="audit-list">{[['deployment.created', 'analytics-cluster', 'Dina Ashraf', '2 min ago'], ['settings.updated', 'Default deployment region', 'Dina Ashraf', '18 min ago'], ['incident.acknowledged', 'INC-204', 'Dina Ashraf', '18 min ago'], ['rollback.available', 'web-production', 'System', '1 hour ago']].map(([action, resource, actor, time]) => <div className="audit-row" key={`${action}-${resource}`}><CheckCircle2 size={15} /><div><strong>{action}</strong><span>{resource} · by {actor}</span></div><time>{time}</time></div>)}</div></section>

  if (activeTab === 'Activity') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Activity size={13} />Live activity</span><p className="feature-subtitle">Recent local control-plane events.</p></div><span className="safe-mode-badge"><span className="live-pulse" />Streaming locally</span></div><div className="activity-feed">{[['Just now', 'Deployment queued', 'analytics-cluster · us-east-1'], ['2 min ago', 'Health check passed', 'web-production · HTTP 200'], ['18 min ago', 'Incident acknowledged', 'INC-204 · memory pressure'], ['1 hour ago', 'Rollback snapshot created', 'web-production · main']].map(([time, title, detail]) => <div className="activity-row" key={title}><span className="activity-dot" /><div><strong>{title}</strong><span>{detail}</span></div><time>{time}</time></div>)}</div></section>

  if (activeTab === 'Health Checks') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><CheckCircle2 size={13} />Health checks</span><p className="feature-subtitle">Synthetic checks run in local safe mode.</p></div><button className="primary-action" onClick={() => setNoticeRead(true)}>{noticeRead ? 'Checks completed' : 'Run all checks'}</button></div><div className="health-grid">{[['web-production', 'HTTP 200', '42 ms', 'Healthy'], ['api-production', 'HTTP 200', '68 ms', 'Healthy'], ['analytics-cluster', 'TCP 5432', '312 ms', 'Degraded'], ['worker-queue', 'TCP 443', '51 ms', 'Healthy']].map(([name, check, latency, status]) => <article className="health-card" key={name}><div className="deployment-card-top"><strong>{name}</strong><span className={`status-badge ${status === 'Healthy' ? 'status-success' : 'status-warning'}`}>{status}</span></div><span>{check}</span><strong>{latency}</strong><div className="monitor-bar"><i className={status !== 'Healthy' ? 'health-degraded' : ''} /></div></article>)}</div></section>

  if (activeTab === 'Environment comparison') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Network size={13} />Environment comparison</span><p className="feature-subtitle">Compare Production and Staging before promoting changes.</p></div></div><div className="comparison-table"><div className="comparison-head"><span>Configuration</span><strong>Production</strong><strong>Staging</strong><span>Diff</span></div>{[['Region', 'us-east-1', 'eu-west-1', 'Changed'], ['Runtime', 'Node.js 20', 'Node.js 20', 'Match'], ['Capacity', '2 vCPU · 4 GB', '1 vCPU · 1 GB', 'Changed'], ['Health check', 'HTTP 200 / 30s', 'HTTP 200 / 60s', 'Changed']].map(([key, production, staging, diff]) => <div className="comparison-row" key={key}><span>{key}</span><strong>{production}</strong><strong>{staging}</strong><span className={diff === 'Match' ? 'diff-match' : 'diff-changed'}>{diff}</span></div>)}</div></section>

  if (activeTab === 'Secrets') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><ShieldCheck size={13} />Secrets manager</span><p className="feature-subtitle">Names and metadata only. Values never render here.</p></div><span className="safe-mode-badge">Local safe mode</span></div><div className="secret-list">{[['DATABASE_URL', 'Production', 'Updated 2 days ago'], ['BETTER_AUTH_SECRET', 'All environments', 'Updated 7 days ago'], ['API_BASE_URL', 'Staging', 'Updated 1 hour ago']].map(([name, scope, updated]) => <div className="secret-row" key={name}><ShieldCheck size={15} /><div><strong>{name}</strong><span>{scope} · {updated}</span></div><button className="secondary-action">Rotate</button></div>)}</div></section>

  if (activeTab === 'Demo scenarios') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Settings2 size={13} />Demo scenarios</span><p className="feature-subtitle">Preview realistic outcomes without external infrastructure.</p></div></div><div className="scenario-grid">{[['Healthy release', 'All checks pass', 'success'], ['Failed build', 'Build error and rollback', 'danger'], ['CPU pressure', 'Anomaly and incident', 'warning'], ['Safe rollback', 'Restore previous snapshot', 'info']].map(([name, detail, tone]) => <button className={`scenario-card scenario-${tone}`} onClick={() => setNoticeRead(true)} key={name}><strong>{name}</strong><span>{detail}</span><small>Run scenario</small></button>)}</div></section>

  if (activeTab === 'Deployments') return <section className="feature-suite"><div className="feature-strip"><span className="safe-mode-badge"><ShieldCheck size={13} />Local Safe Mode</span><span>All changes stay inside this project. No external infrastructure is provisioned.</span><button onClick={() => setShowDemo(true)}><Settings2 size={14} />Demo controls</button></div><div className="feature-toolbar"><div className="search-field"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search deployments, commits, regions" aria-label="Search deployments" /></div><button className="secondary-action" onClick={() => setShowOnboarding(true)}>How it works <ChevronRight size={14} /></button></div><div className="deployment-history-grid">{deployments.filter((deployment) => `${deployment.service} ${deployment.region} ${deployment.commit}`.toLowerCase().includes(query.toLowerCase())).map((deployment) => <article className="deployment-history-card" key={deployment.id}><div className="deployment-card-top"><div className="server-icon"><Server size={16} /></div><span className={`status-badge ${deployment.status === 'Failed' ? 'status-warning' : deployment.status === 'Building' ? 'status-info' : 'status-healthy'}`}><span className="status-dot" />{deployment.status}</span></div><h3>{deployment.service}</h3><p>{deployment.commit} · {deployment.created}</p><div className="deployment-facts"><span>Region<strong>{deployment.region}</strong></span><span>Runtime<strong>{deployment.runtime}</strong></span><span>ID<strong>{deployment.id}</strong></span></div><div className="deployment-card-actions"><button className="secondary-action" onClick={() => navigator.clipboard?.writeText(deployment.id)}><Clipboard size={13} />Copy ID</button><button className="secondary-action" onClick={() => setRollback(deployment.id)}><RotateCcw size={13} />Rollback</button></div></article>)}</div>{rollback && <div className="inline-confirmation"><AlertTriangle size={17} /><span>Rollback {rollback} to the active local snapshot?</span><button onClick={() => setRollback(null)}>Cancel</button><button onClick={() => setRollback(null)}>Confirm rollback</button></div>}{showOnboarding && <Onboarding onClose={() => setShowOnboarding(false)} />}{showDemo && <DemoControls onClose={() => setShowDemo(false)} />}</section>

  if (activeTab === 'Usage') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Activity size={13} />Resource usage</span><p className="feature-subtitle">Free operational telemetry. No prices, charges, or payment data.</p></div><span className="safe-mode-badge"><ShieldCheck size={13} />Free workspace</span></div><div className="usage-grid">{[['CPU time', '18.4 h', '42% average', 'teal'], ['Memory', '6.8 GB·h', '58% average', 'blue'], ['Requests', '1.24M', '1,284 req/s peak', 'purple'], ['Storage', '84 GB', '12% month over month', 'amber']].map(([label, value, detail, tone]) => <article className={`usage-card usage-${tone}`} key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small><div className="usage-bar"><i /></div></article>)}</div><div className="anomaly-banner"><CheckCircle2 size={17} /><div><strong>No billing data collected</strong><span>This workspace tracks operational usage only. It never asks for payment details or sends charges.</span></div></div></section>

  if (activeTab === 'Backups') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Database size={13} />Backup center</span><p className="feature-subtitle">Encrypted metadata snapshots with restore checks.</p></div><button className="primary-action" onClick={() => setNoticeRead(true)}>{noticeRead ? 'Snapshot created' : 'Create snapshot'}</button></div><div className="backup-list">{[['Daily snapshot', 'Today · 03:00 UTC', 'Verified'], ['Weekly archive', 'Sunday · 03:00 UTC', 'Verified'], ['Pre-deployment', 'Yesterday · 14:22 UTC', 'Ready']].map(([name, time, status]) => <div className="backup-row" key={name}><Database size={16} /><div><strong>{name}</strong><span>{time} · Retention 30 days</span></div><span className="status-badge status-success">{status}</span><button className="secondary-action">Verify</button></div>)}</div></section>

  if (activeTab === 'Cost estimator') return <CostEstimator />

  if (activeTab === 'Maintenance') return <MaintenanceView />

  if (activeTab === 'Roles') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><ShieldCheck size={13} />Access roles</span><p className="feature-subtitle">Local workspace permissions for safe collaboration.</p></div></div><div className="roles-grid">{[['Owner', 'Full control', 'Dina Ashraf'], ['Admin', 'Deploy, rollback, and manage alerts', 'Platform team'], ['Developer', 'Create deployments and inspect logs', 'Engineering'], ['Viewer', 'Read-only infrastructure access', 'Observers']].map(([role, access, member]) => <article className="role-card" key={role}><ShieldCheck size={17} /><strong>{role}</strong><span>{access}</span><small>{member}</small><button className="secondary-action">Manage access</button></article>)}</div></section>

  if (activeTab === 'Reports') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><FileText size={13} />Reports & export</span><p className="feature-subtitle">Download a local snapshot of operations data.</p></div><button className="primary-action" onClick={() => { const blob = new Blob([JSON.stringify({ deployments, logs, generatedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'cloud-empire-report.json'; link.click() }}>Export JSON <Download size={14} /></button></div><div className="report-grid"><div><strong>Deployments</strong><span>3 local releases</span></div><div><strong>Logs</strong><span>4 recent events</span></div><div><strong>Incidents</strong><span>2 open items</span></div></div></section>

  if (activeTab === 'Templates') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Zap size={13} />Service templates</span><p className="feature-subtitle">Start deployments with production-shaped defaults.</p></div></div><div className="template-grid">{[['Node.js API', 'Node.js 20 · t3.medium · HTTP'], ['Python worker', 'Python 3.12 · t3.small · TCP'], ['Go service', 'Go 1.23 · m6i.large · HTTP'], ['Static frontend', 'Node.js 22 · t3.micro · CDN']].map(([name, description]) => <button className="template-card" key={name}><Zap size={16} /><strong>{name}</strong><span>{description}</span><small>Use template</small></button>)}</div></section>

  if (activeTab === 'Logs') return <section className="feature-suite"><div className="feature-toolbar"><div className="search-field"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search logs, services, messages" aria-label="Search logs" /></div><select className="region-filter" value={logLevel} onChange={(event) => setLogLevel(event.target.value)}><option>All</option><option>INFO</option><option>WARN</option><option>ERROR</option></select><button className="secondary-action" onClick={() => navigator.clipboard?.writeText(filteredLogs.map((log) => log.join(' · ')).join('\n'))}><Clipboard size={14} />Copy</button><button className="secondary-action" onClick={() => { const blob = new Blob([filteredLogs.map((log) => log.join(' · ')).join('\n')], { type: 'text/plain' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'cloud-empire-logs.txt'; link.click() }}><Download size={14} />Download</button></div><div className="log-console">{filteredLogs.map(([time, level, source, message]) => <div className="log-line" key={`${time}-${source}`}><time>{time}</time><strong className={`log-${level.toLowerCase()}`}>{level}</strong><span>{source}</span><p>{message}</p></div>)}</div></section>

  if (activeTab === 'Monitoring') return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Activity size={13} />Live monitoring</span><p className="feature-subtitle">Live health checks and threshold alerts from imported telemetry.</p></div><div className="segmented">{['24h', '7d', '30d'].map((item) => <button className={range === item ? 'segment-active' : ''} key={item} onClick={() => setRange(item)}>{item}</button>)}</div></div><div className="monitor-grid"><MonitorCard label="CPU utilization" value="42%" threshold="70%" tone="teal" /><MonitorCard label="Memory pressure" value="76%" threshold="75%" tone="amber" /><MonitorCard label="Requests / sec" value="1,284" threshold="2,000" tone="blue" /><MonitorCard label="Network" value="84 Mbps" threshold="120 Mbps" tone="purple" /></div><div className="anomaly-banner"><AlertTriangle size={17} /><div><strong>1 anomaly detected</strong><span>analytics-cluster memory crossed its configured threshold in the selected {range} window.</span></div><button className="secondary-action">Review alert</button></div></section>

  if (activeTab === 'Notifications') return <section className="feature-suite"><div className="notification-center"><div className="notification-center-header"><div><span className="eyebrow"><Activity size={13} />Notification center</span><h2>Workspace alerts</h2></div><button className="secondary-action" onClick={() => setNoticeRead(true)}>{noticeRead ? 'All read' : 'Mark all read'}</button></div>{[['Deployment ready', 'analytics-cluster is ready in us-east-1', '2 min ago'], ['Memory threshold crossed', 'analytics-cluster reached 76% memory', '18 min ago'], ['Rollback available', 'web-production has a safe snapshot', '1 hour ago']].map(([title, message, time], index) => <div className={`notification-row ${noticeRead || index > 0 ? 'notification-read' : ''}`} key={String(title)}>{index === 0 ? <CheckCircle2 size={17} /> : index === 1 ? <AlertTriangle size={17} /> : <RotateCcw size={17} />}<div><strong>{title}</strong><span>{message}</span></div><time>{time}</time></div>)}</div></section>

  if (activeTab === 'Settings') return <section className="feature-suite"><div className="settings-grid"><SettingsCard title="Default deployment" description="Choose safe defaults for new releases" options={['us-east-1', 'eu-west-1', 'us-west-2', 'ap-southeast-1']} /><SettingsCard title="Interface density" description="Tune the amount of information on screen" options={['Comfortable', 'Compact', 'Focus', 'Data dense']} /><SettingsCard title="Chart range" description="Default monitoring time window" options={['24 hours', '7 days', '30 days', 'Custom']} /></div><div className="demo-mode-card"><ShieldCheck size={19} /><div><strong>Local Safe Mode is active</strong><span>Resources are simulated and stored within the project. No billing, cloud credentials, or external infrastructure are used.</span></div><button className="secondary-action" onClick={() => setShowDemo(true)}>Manage demo data</button></div>{showDemo && <DemoControls onClose={() => setShowDemo(false)} />}</section>

  return <section className="feature-suite feature-empty"><Terminal size={18} /><div><strong>{activeTab} workspace</strong><span>Use the controls above to inspect local-safe resources. {serverCount} virtual servers are available.</span></div></section>
}

function CostEstimator() { const [region, setRegion] = useState('us-east-1'); const [instance, setInstance] = useState('t3.medium'); const [hours, setHours] = useState('730'); const price = region === 'eu-west-1' ? 0.052 : region === 'ap-southeast-1' ? 0.058 : instance === 'm6i.large' ? 0.096 : instance === 't3.small' ? 0.021 : 0.042; return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><CircleGauge size={13} />Cost estimator</span><p className="feature-subtitle">Transparent local estimates. No billing account or charges.</p></div><span className="safe-mode-badge"><ShieldCheck size={13} />Estimate only</span></div><div className="cost-estimator"><label>Region<select value={region} onChange={(event) => setRegion(event.target.value)}><option>us-east-1</option><option>eu-west-1</option><option>ap-southeast-1</option></select></label><label>Instance<select value={instance} onChange={(event) => setInstance(event.target.value)}><option>t3.small</option><option>t3.medium</option><option>m6i.large</option></select></label><label>Monthly hours<input type="number" value={hours} onChange={(event) => setHours(event.target.value)} /></label><div className="cost-result"><span>Estimated monthly compute</span><strong>${(price * Number(hours || 0)).toFixed(2)}</strong><small>${price.toFixed(3)}/hour · local estimate</small></div></div></section> }
function MaintenanceView() { const [scheduled, setScheduled] = useState(false); return <section className="feature-suite"><div className="feature-toolbar"><div><span className="eyebrow"><Settings2 size={13} />Maintenance windows</span><p className="feature-subtitle">Schedule safe local maintenance and keep the timeline visible.</p></div><button className="primary-action" onClick={() => setScheduled(!scheduled)}>{scheduled ? 'Window scheduled' : 'Schedule window'}</button></div><div className="maintenance-card"><div><strong>{scheduled ? 'Tonight · 02:00–02:30 UTC' : 'No maintenance windows scheduled'}</strong><span>{scheduled ? 'analytics-cluster · rolling restart · owner Dina Ashraf' : 'Create a window to pause noisy alerts during planned work.'}</span></div><span className="status-badge status-info">{scheduled ? 'Scheduled' : 'Available'}</span></div></section> }

function MonitorCard({ label, value, threshold, tone }: { label: string; value: string; threshold: string; tone: string }) { return <div className={`monitor-card monitor-${tone}`}><span>{label}</span><strong>{value}</strong><small>Threshold {threshold}</small><div className="monitor-bar"><i /></div></div> }
function SettingsCard({ title, description, options }: { title: string; description: string; options: string[] }) { const [selected, setSelected] = useState(options[0]); return <div className="settings-card"><div><strong>{title}</strong><span>{description}</span></div><select value={selected} onChange={(event) => setSelected(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></div> }
function Onboarding({ onClose }: { onClose: () => void }) { return <div className="feature-overlay"><div className="onboarding-card"><button className="icon-button" onClick={onClose} aria-label="Close onboarding"><X size={18} /></button><span className="eyebrow"><ShieldCheck size={13} />Local cloud control plane</span><h2>Build, inspect, and roll back safely</h2><p>Create a deployment with your own region, runtime, capacity, health checks, and commit. Every change is visible on the map and can be rolled back locally.</p><div className="onboarding-steps"><span>1. Configure</span><span>2. Deploy</span><span>3. Monitor</span><span>4. Roll back</span></div><button className="primary-action" onClick={onClose}>Start exploring</button></div></div> }
function DemoControls({ onClose }: { onClose: () => void }) { return <div className="feature-overlay"><div className="onboarding-card"><button className="icon-button" onClick={onClose} aria-label="Close demo controls"><X size={18} /></button><span className="eyebrow"><ShieldCheck size={13} />Demo mode</span><h2>Local Safe Mode</h2><p>This project never provisions AWS, Stripe, or paid infrastructure. Resetting demo data returns the dashboard to its initial state.</p><div className="demo-actions"><button className="secondary-action" onClick={onClose}>Cancel</button><button className="primary-action" onClick={onClose}>Reset demo data</button></div></div></div> }

export default ControlCenter
